SELECT  [customer_id]
      ,[first_name]
      ,[last_name]
      ,[full_name]
      ,[gender]
      ,[birth_date]
      ,[age]
      ,[age_band]
      ,[phone]
      ,[email]
      ,[county]
      ,[town]
      ,[customer_segment]
      ,[acquisition_channel]
      ,[registration_date]
      ,[churn_date]
      ,[loyalty_tier]
      ,[communication_preferences]
      ,[feedback_score]
      ,[home_county]
      ,[primary_store_id]
      ,[visits_to_primary_store]
      ,[is_churned]
      ,[tenure_days]
      ,[tenure_months]
      ,[tenure_band]
      ,[registration_year]
      ,[registration_month]
      ,[registration_quarter]
      ,[email_domain]
      ,[phone_prefix]
      ,[is_phone_valid]
      ,[is_email_valid]
  INTO gold.dim_customers
  FROM [Blue_canopy].[silver].[crm]

--DROP TABLE gold.dim_customers
